### ISSUE TITLE
Pictures and Icons broken in 4.2.0

### ISSUE THREAD

**Issue by TMTwatch** [cinnyapp/cinny-desktop#348] opened 2024-09-13 14:09 UTC
### Describe the bug

I recently updated to 4.2.0 and all the channel room and user icons including mine are missing. I tried removing Cinny desktop and reinstalling but it's the same. This bug affects both Mac and Windows apps. Here is what my profile picture looks like in Cinny. It does show properly in all my Element clients. Investigating further it seems that ALL pictures are broken. If I scroll in backchat those pictures are also not loading. Photos attached

<img width="123" alt="Screenshot 2024-09-13 at 10 04 25 AM" src="https://github.com/user-attachments/assets/cb3b27ee-6b21-4ed5-a74a-6d8017063a92">
<img width="628" alt="Screenshot 2024-09-13 at 10 06 52 AM" src="https://github.com/user-attachments/assets/bc99ceb2-3d35-4de3-8182-b87bd4f78f97">

### Reproduction

install 4.2.0.
Icons and pictures are missing

### Expected behavior

Icons and pictures should show just like they always did

### Platform and versions

```shell
Windows 11 Pro(v10.0.22631) / MacOS 14.6.1
Cinny 4.2.0
Matrix Homeserver - Synapse
Github
```

**Comment by kfiven** [comment] 2024-09-13 14:16
duplicate of https://github.com/cinnyapp/cinny-desktop/issues/344

**Closed as not planned by kfiven** 2024-09-13 14:16 UTC
