### ISSUE TITLE
Show room image next to it's name

### ISSUE THREAD

**Issue by rwjack** [cinnyapp/cinny-desktop#188] opened 2023-07-23 17:03 UTC
### Describe the problem

Easier to find a room visually when an image is next to it.

### Describe the solution you'd like

Similar to element/discord:

![image](https://github.com/cinnyapp/cinny-desktop/assets/59068073/f6176171-a13e-4c63-8902-c6ebb4a338b4)

**Comment by kfiven** [comment] 2023-07-23 23:16
Duplicate of https://github.com/cinnyapp/cinny/issues/107

**Closed as completed by kfiven** 2023-07-23 23:16 UTC
