### ISSUE TITLE
Cinny Desktop appears blurry on KDE Wayland

### ISSUE THREAD

**Issue by regalialong** [cinnyapp/cinny-desktop#332] opened 2024-08-10 21:01 UTC
### Describe the bug

On my system, the Desktop version appears slightly blurry compared to Firefox.

I'm struggling on how to show this.
Here is a screenshot in my browser:
![image](https://github.com/user-attachments/assets/1287f553-12da-4ab4-bff4-631ea9de3080)
And here from Cinny Desktop:
![image](https://github.com/user-attachments/assets/f55f041b-a3f8-4850-95a9-4403b542c9bb) 

The difference is probably most extreme on the source code button:
![image](https://github.com/user-attachments/assets/559905fb-9e3c-4f50-95d7-3b3e6e9525a0)

This makes using Cinny Desktop a very tiring experience because text is not easily legible.

### Reproduction

1. Start Cinny Desktop
2. Make the window larger
3. Now I appear to have dropped my glasses

### Platform and versions

```shell
OS: Arch Linux
DE: Plasma 6.1.3
Cinny version: v4.1.0
Downloaded from: AUR (cinny-desktop-bin, so Github deb)
```

### Additional context

This appears to be some issue with window scale, because it's fine when the window is unscaled.

A workaround I found is using xwayland per `WAYLAND_DISPLAY=`, which requires `WEBKIT_DISABLE_DMABUF_RENDERER=1` due to the rending issues discussed in #227 but that isn't a solution.

**Comment by ogarcia** [comment] 2024-10-07 11:13
@regalialong in this case the problem is not Cinny's, it's WebKit's, this is the upstream bug: https://bugs.webkit.org/show_bug.cgi?id=263645

**Comment by kfiven** [comment] 2024-10-07 11:50
Closing as per above.

**Closed as not planned by kfiven** 2024-10-07 11:50 UTC

**Comment by regalialong** [comment] 2024-10-08 20:29
Ah, the unfortunate state of WebKitGTK....
