### ISSUE TITLE
Add favourites list or enable room reordering

### ISSUE THREAD

**Issue by rwjack** [cinnyapp/cinny-desktop#189] opened 2023-07-23 17:06 UTC
### Describe the problem

> I'm always frustrated when...

I can't order the room list exactly how I want it to be.

### Describe the solution you'd like

Similar drag & drop functionality as slack/discord.

**Comment by kfiven** [comment] 2023-07-23 23:18
Duplicate of https://github.com/cinnyapp/cinny/issues/44

**Closed as completed by kfiven** 2023-07-23 23:18 UTC
